name: Build and Deploy

on:
  pull_request:
    branches: [ master ]

env:
  DOCKER_IMAGE_NAME: rob-derosa-tic-tac-toe-img
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_RESOURCE_GROUP: tic-tac-toe-rg
  AZURE_APP_PLAN: tic-tac-toe-serviceplan
  AZURE_WEBAPP_NAME: rob-derosa-tic-tac-toe
  AZURE_LOCATION: '"Central US"'

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    name: Deploy app container to Azure

    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy web app container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: ${{env.IMAGE_REGISTRY_URL}}/${{ github.repository }}/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout
