name: Build and Deploy

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build node project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
