name: Build and Deploy

on:
  pull_request:
    branches: [ master ]

env:
  DOCKER_IMAGE_NAME: rob-derosa-tic-tac-toe-img
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_RESOURCE_GROUP: tic-tac-toe-rg
  AZURE_APP_PLAN: tic-tac-toe-serviceplan
  AZURE_WEBAPP_NAME: rob-derosa-tic-tac-toe
  AZURE_LOCATION: '"Central US"'

jobs:
  build:
    name: Build node project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@master
        with:
          name: tic-tac-toe-artifacts
          path: public/

  build-docker-image:
    name: Build image and store in GitHub Packages container registry
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download built artifact
        uses: actions/download-artifact@master
        with:
          name: tic-tac-toe-artifacts
          path: public/

      - name: Create image and store in Packages
        uses: mattdavis0351/actions/docker-gpr@1.3.0
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          image-name: ${{env.DOCKER_IMAGE_NAME}}
          
  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-docker-image
    name: Deploy app container to Azure

    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy web app container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: ${{env.IMAGE_REGISTRY_URL}}/${{ github.repository }}/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout
