name: Destroy Azure environment

on:
  workflow_dispatch:
    inputs:
        
env:
  AZURE_RESOURCE_GROUP: tic-tac-toe-rg

jobs:

  destroy-azure-resources:
    name: Destroy Azure environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy Azure environment
        if: success()
        run: |
          az group delete --name ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} --yes
