name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Web App Name'     
        required: true
        default: 'warning'
      tags:
        description: 'Comments'
        
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
